
[평균] 1-표본 t-검정
=======================================================================


Sidebar Inputs {.sidebar}
-----------------------------------------------------------------------

```{r one-sample-ui}

tags$br()
tags$b("데이터")

textInput("sample_onemean", "표본", value = "3,7,11,0,7,0,4,5,6,2", 
          placeholder = "콤마로 구분된 숫자를 입력하세요. 예를 들어, 7.2, 4.7, 5, 5.03, 등")
tags$p("※ 콤마로 구분된 숫자 입력. ex) 7.2, 4.7, 5.03, 등")

tags$br()

tags$b("가설검정")

tags$p("1. 귀무가설")
tags$p("\\( H_0 : \\mu = \\)")

numericInput("onemean_h0",
             label = NULL,
             value = 3, step = 0.1, width="100px")

tags$p("2. 검정방향")
radioButtons(
  inputId = "onemean_alternative",
  label = "대립가설",
  inline = TRUE,
  choices = c(
    "\\( \\neq \\)" = "two.sided",
    "\\( > \\)" = "greater",
    "\\( < \\)" = "less"
  )
)

tags$p("3. 모집단 분산")
checkboxInput("popsd_onemean", "모집단 분산을 알는 경우:", FALSE)
conditionalPanel(
  condition = "input.popsd_onemean == 1",
  numericInput("sigma2_onemean", "\\(\\sigma^2 = \\)",
               value = 2, min = 0, step = 0.1, width = "100px")
)

tags$p("4. 유의수준")
sliderInput("onemean_alpha",
            "유의수준 \\(\\alpha = \\)",
            min = 0.01,
            max = 0.20,
            value = 0.05
)

tags$br()

tags$b("데이터와 코드 출처")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-t-test.html", "ㄴ 데이터: t-검정, ")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-z-confidence-interval.html", "ㄴ 데이터: z-검정")
tags$br()
tags$a(href="https://statsandr.com/blog/a-shiny-app-for-inferential-statistics-by-hand/", "ㄴ 코드")


```

Column {data-width=400}
-------------------------------------

### 가설검정


```{r one-mean-statistics}

renderUI({
  dat <- extract(input$sample_onemean)
  if (anyNA(dat) | length(dat) < 2) {
    "Invalid input or not enough observations"
  } else if ( input$popsd_onemean == FALSE) {
    
    test_confint <- t.test(x = dat, mu = input$onemean_h0, alternative = "two.sided", conf.level = 1 - input$onemean_alpha)
    test <- t.test(x = dat, mu = input$onemean_h0, alternative = input$onemean_alternative, conf.level = 1 - input$onemean_alpha)
    
    withMathJax(
      tags$h2("가. 표본 데이터"),
      br(),
      paste("관측점: ", c(paste(dat, collapse = ", ")), collapse = " "),
      br(),
      paste0("\\(n =\\) ", length(dat)),
      br(),
      paste0("\\(\\bar{x} =\\) ", round(mean(dat), 3)),
      br(),
      paste0("\\(s =\\) ", round(sd(dat), 3)),
      br(),
      br(),
      tags$h2("나. 신뢰구간(양측)"),
      br(),
      paste0(
        (1 - input$onemean_alpha) * 100, 
        "% 신뢰구간: \\(\\mu = \\bar{x} \\pm t_{\\alpha/2, n - 1} \\dfrac{s}{\\sqrt{n}} \\) "),
      br(),
      paste0(
        " = ",
        round(test_confint$estimate, 3), 
        " \\( \\pm \\) ", "\\( ( \\)", 
        round(qt(input$onemean_alpha / 2, df = test_confint$parameter, lower.tail = FALSE), 3), 
        " * ", 
        round(test_confint$stderr * sqrt(length(dat)), 3), " / ", round(sqrt(length(dat)), 3), 
        "\\( ) \\) ", "\\(  \\) \n"),
      br(),
      paste0(
        "= [", round(test_confint$conf.int[1], 3), "; ", 
        round(test_confint$conf.int[2], 3), "]"
      ),
      br(),
      br(),
      tags$h2("다. 가설검정"),
      br(),
      paste0("1. \\(H_0 : \\mu = \\) ", test$null.value, " vs. \\(H_1 : \\mu \\) ", 
             ifelse(input$onemean_alternative == "two.sided", "\\( \\neq \\) ", 
             ifelse(input$onemean_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
      br(),
      paste0(
        "2. 검정 통계량 : \\(t_{관측점} = \\dfrac{\\bar{x} - \\mu_0}{s / \\sqrt{n}} = \\) ",
        "(", round(test$estimate, 3), ifelse(test$null.value >= 0, 
                                             paste0(" - ", test$null.value), 
                                             paste0(" + ", abs(test$null.value))), ") / ", round(test$stderr, 3), " \\( = \\) ",
        round(test$statistic, 3)
      ),
      br(),
      paste0(
        "3. 임계값 :", 
        ifelse(input$onemean_alternative == "two.sided", " \\( \\pm t_{\\alpha/2, n - 1} = \\pm t(\\)", 
        ifelse(input$onemean_alternative == "greater", " \\( t_{\\alpha, n - 1} = t(\\)", " \\( -t_{\\alpha, n - 1} = -t(\\)")),
        ifelse(input$onemean_alternative == "two.sided", input$onemean_alpha / 2, input$onemean_alpha), ", ", test$parameter, "\\()\\)", " \\( = \\) ",
        ifelse(input$onemean_alternative == "two.sided", "\\( \\pm \\)", 
               ifelse(input$onemean_alternative == "greater", "", " -")),
        ifelse(input$onemean_alternative == "two.sided", round(qt(input$onemean_alpha / 2, df = test$parameter, lower.tail = FALSE), 3), 
               round(qt(input$onemean_alpha, df = test$parameter, lower.tail = FALSE), 3))
      ),
      br(),
      
      paste0("4. 결론 : ", ifelse(test$p.value < input$onemean_alpha, "\\(H_0\\) 기각함", "\\(H_0\\) 기각 못함")),
      br(),
      br(),
      
      tags$h2("라. 해석"),
      br(),
      glue::glue("유의수준 {input$onemean_alpha * 100} % 에서, 참 평균이 {test$null.value} 이라는 귀무가설을 ",
                 "{ifelse(test$p.value < input$onemean_alpha, '기각한다.', '기각하지 못한다.')}",
                 "\\((p\\)-값 = ", "{ifelse(test$p.value < 0.001, '< 0.001', round(test$p.value, 3))} )")
    )
  } else if ( input$popsd_onemean == TRUE) {
    
    test <- t.test2(x = dat, V = input$sigma2_onemean, m0 = input$onemean_h0, alpha = input$onemean_alpha, alternative = input$onemean_alternative)
    
    withMathJax(
      
      # 표본데이터 ------------------------------------------------------------------
      
      tags$h2("표본 데이터"),
      br(),
      paste("관측점: ", c(paste(dat, collapse = ", ")), collapse = " "),
      br(),
      paste0("\\(n =\\) ", length(dat)),
      br(),
      paste0("\\(\\bar{x} =\\) ", round(mean(dat), 3)),
      br(),
      paste0("\\(\\sigma =\\) ", round(sqrt(input$sigma2_onemean), 3)),
      br(),
      br(),
      
      # 신뢰구간 ------------------------------------------------------------------
      
      tags$h2("신뢰구간(양측)"),
      br(),
      paste0(
        (1 - input$onemean_alpha) * 100, 
        "% 신뢰구간: \\(\\mu = \\bar{x} \\pm z_{\\alpha/2} \\dfrac{\\sigma}{\\sqrt{n}} \\) "),
      br(),
      paste0(
        " = ",        
        round(test$mean, 3), 
        "  \\( \\pm \\)", " \\( ( \\)", 
        round(qnorm(input$onemean_alpha / 2, lower.tail = FALSE), 3), 
        " * ", 
        round(test$sigma, 3), " / ", round(sqrt(length(dat)), 3), "\\( ) \\) ", "\\( \\)"),
      br(),
      paste0(
        "= [", round(test$LCL, 3), "; ", round(test$UCL, 3), "]"
      ),
      br(),
      br(),
      
      # 가설검정 ------------------------------------------------------------------
      
      tags$h2("가설검정"),
      br(),
      paste0("1. \\(H_0 : \\mu = \\) ", input$onemean_h0, " vs. \\(H_1 : \\mu \\) ", ifelse(input$onemean_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$onemean_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), input$onemean_h0),
      br(),
      paste0(
        "2. 검정통계량 : \\(z_{obs} = \\dfrac{\\bar{x} - \\mu_0}{\\sigma / \\sqrt{n}} = \\) ",
        "(", round(test$mean, 3), ifelse(input$onemean_h0 >= 0, paste0(" - ", input$onemean_h0), paste0(" + ", abs(input$onemean_h0))), ") / ", round(test$sigma / sqrt(length(dat)), 3), " \\( = \\) ",
        round(test$statistic, 3)
      ),
      br(),
      
      paste0(
          "3. 임계값 :", ifelse(input$onemean_alternative == "two.sided", " \\( \\pm z_{\\alpha/2} = \\pm z(\\)", ifelse(input$onemean_alternative == "greater", " \\( z_{\\alpha} = z(\\)", " \\( -z_{\\alpha} = -z(\\)")),
          ifelse(input$onemean_alternative == "two.sided", input$onemean_alpha / 2, input$onemean_alpha), "\\()\\)", " \\( = \\) ",
          ifelse(input$onemean_alternative == "two.sided", "\\( \\pm \\)", ifelse(input$onemean_alternative == "greater", "", " -")),
          ifelse(input$onemean_alternative == "two.sided", round(qnorm(input$onemean_alpha / 2, lower.tail = FALSE), 3), round(qnorm(input$onemean_alpha, lower.tail = FALSE), 3))
        ),
      br(),
      
      paste0("4. 결론 : ", ifelse(test$p.value < input$onemean_alpha, "\\(H_0\\) 기각함", "\\(H_0\\) 기각 못함")),
      br(),
      br(),
      
      # 해석 -------------------------------------------------------------------------------------
      
      tags$h2("해석"),

      paste0("유의수준 ", input$onemean_alpha * 100, "% 에서, ", 
             "참 평균이 ", input$onemean_h0, " 이라는 귀무가설을 ", ifelse(test$p.value < input$onemean_alpha, "기각한다", "기각하지 못한다"),
             " \\((p\\)-값 ",
             paste0("\\(=\\) ", round(test$p.value, 3)), ")", ".")
            
  )} else {
    print("loading...")
  }
})
  
```

Column {data-width=400}
-------------------------------------
   
### 시각화

```{r, out.width="100%", out.height="100%", eval = FALSE}
renderPlotly({

test_g <- ggplot(NULL, aes(c(-5,5))) +
 geom_area(stat = "function", fun = dnorm, fill="sky blue", xlim = c(-5, 5)) +
  geom_area(stat = "function", fun = dnorm,  xlim = c(-1.35, 5)) +
 ggtitle("Normal Distribution")

plotly::ggplotly(test_g)
  
})

```


```{r one-mean-viz, out.width="100%", eval = TRUE}
renderPlotly({  
    if ( input$popsd_onemean == FALSE) {
      dat <- extract(input$sample_onemean)
      test <- t.test(x = dat, mu = input$onemean_h0, alternative = input$onemean_alternative, conf.level = 1 - input$onemean_alpha)
      if (input$onemean_alternative == "two.sided") {
        funcShaded <- function(x) {
          y <- dt(x, df = test$parameter)
          y[x < qt(input$onemean_alpha / 2, df = test$parameter, lower.tail = FALSE) & x > qt(input$onemean_alpha / 2, df = test$parameter) ] <- NA
          return(y)
        }
      } else if (input$onemean_alternative == "greater") {
        funcShaded <- function(x) {
          y <- dt(x, df = test$parameter)
          y[x < qt(input$onemean_alpha, df = test$parameter, lower.tail = FALSE) ] <- NA
          return(y)
        }
      } else if (input$onemean_alternative == "less") {
        funcShaded <- function(x) {
          y <- dt(x, df = test$parameter)
          y[x > qt(input$onemean_alpha, df = test$parameter, lower.tail = TRUE) ] <- NA
          return(y)
        }
      }
      p <- ggplot(data.frame(x = c(qt(0.999, df = test$parameter, lower.tail = FALSE), 
                                   qt(0.999, df = test$parameter, lower.tail = TRUE))), aes(x = x)) +
        geom_area(stat="function", fun = dt, fill="gray90", args = list(df = test$parameter)) +
        geom_area(stat="function", fun = funcShaded, fill = "sky blue", alpha = 0.8) +
        theme_minimal() +
        geom_vline(xintercept = test$statistic, color = "steelblue") +
        geom_text(aes(x = test$statistic, label = paste0("검정 통계량 = ", round(test$statistic, 3)), y = 0.2), colour = "steelblue", angle = 90, vjust = 1.3, text = element_text(size = 11)) +
        ggtitle(paste0("t-분포 ~", " t(", round(test$parameter, 3), ")")) +
        theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
        ylab("밀도") +
        xlab("x")
      plotly::ggplotly(p)
      # p
    } else if ( input$popsd_onemean == TRUE) {
      dat <- extract(input$sample_onemean)
      test <- t.test2(x = dat, V = input$sigma2_onemean, m0 = input$onemean_h0, alpha = input$onemean_alpha, alternative = input$onemean_alternative)
      if (input$onemean_alternative == "two.sided") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x < qnorm(input$onemean_alpha / 2, mean = 0, sd = 1, lower.tail = FALSE) & x > qnorm(input$onemean_alpha / 2, mean = 0, sd = 1) ] <- NA
          return(y)
        }
      } else if (input$onemean_alternative == "greater") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x < qnorm(input$onemean_alpha, mean = 0, sd = 1, lower.tail = FALSE) ] <- NA
          return(y)
        }
      } else if (input$onemean_alternative == "less") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x > qnorm(input$onemean_alpha, mean = 0, sd = 1, lower.tail = TRUE) ] <- NA
          return(y)
        }
      }
      p <- ggplot(data.frame(x = c(qnorm(0.999, mean = 0, sd = 1, lower.tail = FALSE), qnorm(0.999, mean = 0, sd = 1, lower.tail = TRUE))), aes(x = x)) +
        geom_area(stat="function", fun = dnorm, fill="gray90", args = list(mean = 0, sd = 1)) +
        geom_area(stat="function", fun = funcShaded, fill = "sky blue", alpha = 0.8) +
        theme_minimal() +
        geom_vline(xintercept = test$statistic, color = "steelblue") +
        geom_text(aes(x = test$statistic, label = paste0("검정통계량 = ", round(test$statistic, 3)), y = 0.2), colour = "steelblue", angle = 90, vjust = 1.3, text = element_text(size = 11)) +
        ggtitle(paste0("정규분포 N(0,1)")) +
        theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
        ylab("밀도") +
        xlab("x")
      plotly::ggplotly(p)
    } 
  } )


```


### 데이터


```{r one-mean-data}
t.test2 <- function(x, V, m0 = 0, alpha = 0.05, alternative = "two.sided") {
  M <- mean(x)
  n <- length(x)
  sigma <- sqrt(V)
  S <- sqrt(V / n)
  statistic <- (M - m0) / S
  p <- if (alternative == "two.sided") {
    2 * pnorm(abs(statistic), lower.tail = FALSE)
  } else if (alternative == "less") {
    pnorm(statistic, lower.tail = TRUE)
  } else {
    pnorm(statistic, lower.tail = FALSE)
  }
  # p <- (1 - pnorm((M-m0)/S))
  LCL <- (M - S * qnorm(1 - alpha / 2))
  UCL <- (M + S * qnorm(1 - alpha / 2))
  value <- list(mean = M, m0 = m0, sigma = sigma, statistic = statistic, p.value = p, LCL = LCL, UCL = UCL, alternative = alternative)
  # print(sprintf("P-value = %g",p))
  # print(sprintf("Lower %.2f%% Confidence Limit = %g",
  #               alpha, LCL))
  # print(sprintf("Upper %.2f%% Confidence Limit = %g",
  #               alpha, UCL))
  return(value)
}

extract <- function(text) {
  text <- gsub(" ", "", text)
  split <- strsplit(text, ",", fixed = FALSE)[[1]]
  as.numeric(split)
}

renderTable({
dat <- extract(input$sample_onemean) 

dat %>% as.data.frame() %>% 
  set_names("표본") %>% 
  xtable::xtable(align="cc")
  
})
```


