

[분산] 1-변수 분산 카이제곱-검정
=======================================================================

Sidebar Inputs {.sidebar}
-----------------------------------------------------------------------

```{r one-variance-ui}

tags$br()
tags$b("데이터")

textInput("onevar_sample", "표본", value = "0.9, -0.8, 0.1, -0.3, 0.2")

tags$p("※ 콤마로 구분된 숫자 입력. ex) 7.2, 4.7, 5.03, 등")

tags$b("가설검정")

tags$p("1. 귀무가설")
tags$p("\\( H_0 : \\sigma^2 = \\)")

numericInput("onevar_h0",
             label = NULL,
             value = 0.1, step = 0.1, width="100px")

tags$p("2. 검정방향")
radioButtons(
  inputId = "onevar_alternative",
  label = "대립가설",
  inline = TRUE,
  choices = c(
    "\\( \\neq \\)" = "two.sided",
    "\\( > \\)" = "greater",
    "\\( < \\)" = "less"
  )
)


tags$p("4. 유의수준")
sliderInput("onevar_alpha",
            "유의수준 \\(\\alpha = \\)",
            min = 0.01,
            max = 0.20,
            value = 0.05
)

tags$br()

tags$b("데이터와 코드 출처")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-t-test.html", "ㄴ 데이터: t-검정, ")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-z-confidence-interval.html", "ㄴ 데이터: z-검정")
tags$br()
tags$a(href="https://statsandr.com/blog/a-shiny-app-for-inferential-statistics-by-hand/", "ㄴ 코드")


```

Column {data-width=400}
-------------------------------------

### 가설검정


```{r one-variance-statistics}

renderUI({
    dat <- extract(input$onevar_sample)
    if (anyNA(dat) | length(dat) < 2) {
      "Invalid input or not enough observations"
    } else if (input$onevar_h0 <= 0) {
      withMathJax(
        sprintf("\\( \\sigma^2_0 \\) must be > 0")
      )
    } else {
      test_confint <- varTest(x = dat, sigma.squared = input$onevar_h0, alternative = "two.sided", conf.level = 1 - input$onevar_alpha)
      test <- varTest(x = dat, sigma.squared = input$onevar_h0, alternative = input$onevar_alternative, conf.level = 1 - input$onevar_alpha)
      withMathJax(
        tags$h2("데이터"),
        br(),
        paste("데이터 = ", c(paste(dat, collapse = ", ")), collapse = " "),
        br(),
        paste0("\\(n =\\) ", length(dat)),
        br(),
        paste0("\\(s^2 =\\) ", round(var(dat), 3)),
        br(),
        paste0("\\(s =\\) ", round(sd(dat), 3)),
        br(),
        br(),
        tags$h2("신뢰구간 - 양측"),
        br(),
        paste0(
          "신뢰구간 ", (1 - input$onevar_alpha) * 100, "% 에 대해  \\(\\sigma^2 = \\Bigg[ \\dfrac{(n-1)s^2}{\\chi^2_{\\alpha/2, n-1}} ; \\dfrac{(n-1)s^2}{\\chi^2_{1-\\alpha/2, n-1}} \\Bigg] = \\) ",
          "[(", round((length(dat) - 1) * test$estimate, 3), " / ", round(qchisq(input$onevar_alpha / 2, df = test$parameters, lower.tail = FALSE), 3), ") ; (", round((length(dat) - 1) * test$estimate, 3), " / ", round(qchisq(input$onevar_alpha / 2, df = test$parameters, lower.tail = TRUE), 3), ")] = ",
          "[", round(test_confint$conf.int[1], 3), "; ", round(test_confint$conf.int[2], 3), "]"
        ),
        br(),
        br(),
        tags$h2("가설 검정"),
        br(),
        paste0("1. \\(H_0 : \\sigma^2 = \\) ", test$null.value, " and \\(H_1 : \\sigma^2 \\) ", ifelse(input$onevar_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$onevar_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
        br(),
        paste0(
          "2. 검정통계량 : \\(\\chi^2_{obs} = \\dfrac{(n-1)s^2}{\\sigma^2_0} = \\) ",
          "[(", length(dat), " - 1) * ", round(test$estimate, 3), "] / ", test$null.value, " \\( = \\) ",
          round(test$statistic, 3)
        ),
        br(),
        if (input$onevar_alternative == "two.sided") {
          withMathJax(
            paste0("3. 임계값 : \\( \\chi^2_{1-\\alpha/2, n - 1} \\) and \\( \\chi^2_{\\alpha/2, n - 1} =\\) "),
            paste0("\\( \\chi^2 \\)(", 1 - input$onevar_alpha / 2, ", ", test$parameters, ") and \\( \\chi^2 \\)(", input$onevar_alpha / 2, ", ", test$parameters, ") = "),
            paste0(round(qchisq(1 - input$onevar_alpha / 2, df = test$parameters, lower.tail = FALSE), 3), " and ", round(qchisq(input$onevar_alpha / 2, df = test$parameters, lower.tail = FALSE), 3))
          )
        } else if (input$onevar_alternative == "greater") {
          withMathJax(
            paste0("3. 임계값 : \\( \\chi^2_{\\alpha, n - 1} =\\) "),
            paste0("\\( \\chi^2 \\)(", input$onevar_alpha, ", ", test$parameters, ") = "),
            paste0(round(qchisq(input$onevar_alpha, df = test$parameters, lower.tail = FALSE), 3))
          )
        } else {
          withMathJax(
            paste0("3. 임계값 : \\( \\chi^2_{1-\\alpha, n - 1} =\\) "),
            paste0("\\( \\chi^2 \\)(", 1 - input$onevar_alpha, ", ", test$parameters, ") = "),
            paste0(round(qchisq(1 - input$onevar_alpha, df = test$parameters, lower.tail = FALSE), 3))
          )
        },
        br(),
        paste0("4. 결론 : ", ifelse(test$p.value < input$onevar_alpha, "\\(H_0\\) 기각", "\\(H_0\\) 기각 못함")),
        br(),
        br(),
        tags$h2("해석"),
        br(),
        paste0( input$onevar_alpha * 100, "% 유의수준에서, ", 
        "참 분산 비율이 ", test$null.value, " 이라는 귀무가설을 ", 
        ifelse(test$p.value < input$onevar_alpha, "기각한다", "기각하지 않는다"), 
        " \\((p\\)-값 ", ifelse(test$p.value < 0.001, "< 0.001", paste0("\\(=\\) ", round(test$p.value, 3))), ")", ".")
                
      )
    } 
  })
  
```

Column {data-width=400}
-------------------------------------
   
### 시각화


```{r one-variance-viz, out.width="100%", eval = TRUE}
renderPlotly({  
      dat <- extract(input$onevar_sample)
      test <- varTest(x = dat, sigma.squared = input$onevar_h0, 
                      alternative = input$onevar_alternative, conf.level = 1 - input$onevar_alpha)

      if (input$onevar_alternative == "two.sided") {
        funcShaded <- function(x) {
          y <- dchisq(x, df = test$parameters)
          y[x > qchisq(1 - input$onevar_alpha / 2, df = test$parameters, lower.tail = FALSE) & x < qchisq(1 - input$onevar_alpha / 2, df = test$parameters, lower.tail = TRUE)] <- NA
          return(y)
        }
      } else if (input$onevar_alternative == "greater") {
        funcShaded <- function(x) {
          y <- dchisq(x, df = test$parameters)
          y[x < qchisq(input$onevar_alpha, df = test$parameters, lower.tail = FALSE)] <- NA
          return(y)
        }
      } else if (input$onevar_alternative == "less") {
        funcShaded <- function(x) {
          y <- dchisq(x, df = test$parameters)
          y[x > qchisq(1 - input$onevar_alpha, df = test$parameters, lower.tail = FALSE)] <- NA
          return(y)
        }
      }
      p <- data.frame(x = seq(0, qchisq(0.999, df = test$parameters, lower.tail = TRUE), 0.1)) %>% 
        ggplot( aes(x = x) ) +
          geom_area(stat="function", fun = dchisq, fill="gray90", args = list(df = test$parameter)) +
          geom_area(stat="function", fun = funcShaded, fill = "sky blue", alpha = 0.8) +
          theme_minimal() +
          geom_vline(xintercept = test$statistic, color = "steelblue") +
          geom_text(aes(x = test$statistic, label = paste0("검정 통계량 = ", round(test$statistic, 3)), y = 0.025), 
                    colour = "steelblue", angle = 90, vjust = 1.3, text = element_text(size = 11)) +
          theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
          labs(title = glue::glue("카이제곱 분포 (df = {test$parameters})"),
               y = "밀도",
               x = "x")
      plotly::ggplotly(p)
  })


```


### 데이터


```{r one-variance-data}

extract <- function(text) {
  text <- gsub(" ", "", text)
  split <- strsplit(text, ",", fixed = FALSE)[[1]]
  as.numeric(split)
}

renderTable({
  var_dat <- extract(input$onevar_sample)


tibble(변수 = var_dat) %>% 
  xtable::xtable(align="cc")
  
})
```


