

[비율] 2-비율 z-검정
=======================================================================


Sidebar Inputs {.sidebar}
-----------------------------------------------------------------------

```{r two-proportion-ui}

tags$br()
tags$b("데이터")
tags$br()

tags$b("표본 크기 1")
numericInput("n1_twoprop", "\\(n_1 = \\)",
             value = 30, min = 0, step = 1)
tags$b("표본 크기 2")
numericInput("n2_twoprop", "\\(n_2 = \\)",
             value = 30, min = 0, step = 1)
tags$hr()

radioButtons(
  inputId = "propx_twoprop",
  label = NULL,
  choices = c(
    "성공 비율 \\(\\hat{p}\\)" = "prop_true",
    "성공 횟수 \\(x\\)" = "prop_false"
  )
)

conditionalPanel(
  condition = "input.propx_twoprop == 'prop_true'",
  tags$b("성공 비율"),
  numericInput("p1_twoprop", "\\(\\hat{p}_1 = \\)",
               value = 0.2, min = 0, max = 1, step = 0.01
  ),
  numericInput("p2_twoprop", "\\(\\hat{p}_2 = \\)",
               value = 0.3, min = 0, max = 1, step = 0.01
  )
)
conditionalPanel(
  condition = "input.propx_twoprop == 'prop_false'",
  tags$b("성공 횟수"),
  numericInput("x1_twoprop", "\\(x_1 = \\)",
               value = 10, min = 0, step = 1
  ),
  numericInput("x2_twoprop", "\\(x_2 = \\)",
               value = 12, min = 0, step = 1
  )
)


tags$b("가설검정")

tags$p("1. 귀무가설")
tags$p("\\( H_0 : p_1 - p_2 = \\)")

numericInput("twoprop_h0",
             label = NULL,
             value = 0.1, step = 0.1, width="100px")

checkboxInput("pooledstderr_twoprop", "합동(pooled) 표준오차 사용:", FALSE)

tags$p("2. 검정방향")
radioButtons(
  inputId = "twoprop_alternative",
  label = "대립가설",
  inline = TRUE,
  choices = c(
    "\\( \\neq \\)" = "two.sided",
    "\\( > \\)" = "greater",
    "\\( < \\)" = "less"
  )
)


tags$p("4. 유의수준")
sliderInput("twoprop_alpha",
            "유의수준 \\(\\alpha = \\)",
            min = 0.01,
            max = 0.20,
            value = 0.05
)

tags$br()

tags$b("데이터와 코드 출처")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-t-test.html", "ㄴ 데이터: t-검정, ")
tags$br()
tags$a(href="https://cran.r-project.org/web/packages/distributions3/vignettes/one-sample-z-confidence-interval.html", "ㄴ 데이터: z-검정")
tags$br()
tags$a(href="https://statsandr.com/blog/a-shiny-app-for-inferential-statistics-by-hand/", "ㄴ 코드")


```

Column {data-width=400}
-------------------------------------

### 가설검정


```{r two-proprotion-statistics}

renderUI({
    if (input$propx_twoprop == "prop_true" & input$pooledstderr_twoprop == FALSE) {
      test <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = FALSE)
      test_confint <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = "two.sided", pooled.stderr = FALSE)
      withMathJax(
        tags$h2("데이터"),
        br(),
        paste0("\\(n_1 =\\) ", round(test$n1, 3)),
        br(),
        paste0("\\(n_2 =\\) ", round(test$n2, 3)),
        br(),
        paste0("\\(\\hat{p}_1 =\\) ", round(test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{p}_2 =\\) ", round(test$estimate2, 3)),
        br(),
        paste0("\\(\\hat{q}_1 = 1 - \\hat{p}_1 =\\) ", round(1 - test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{q}_2 = 1 - \\hat{p}_2 =\\) ", round(1 - test$estimate2, 3)),
        br(),
        helpText(paste0("\\( n_1\\hat{p}_1 = \\) ", round(test$n1 * test$estimate1, 3), 
                        " 와 \\( n_1(1-\\hat{p}_1) = \\) ", round(test$n1 * (1 - test$estimate1), 3))),
        helpText(paste0("\\( n_2\\hat{p}_2 = \\) ", round(test$n2 * test$estimate2, 3), 
                        " 와 \\( n_2(1-\\hat{p}_2) = \\) ", round(test$n2 * (1 - test$estimate2), 3))),
        helpText(paste0("\\( n_1\\hat{p}_1 \\geq 5\\), \\( n_1(1-\\hat{p}_1) \\geq 5\\), \\( n_2\\hat{p}_2 \\geq 5\\) 와 \\( n_2(1-\\hat{p}_2) \\geq 5\\) 가정이 ", 
                        ifelse(test$n1 * test$estimate1 >= 5 & test$n1 * (1 - test$estimate1) >= 5 & test$n2 * test$estimate2 >= 5 & test$n2 * (1 - test$estimate2) >= 5, " 충족됨.", " 총족되지 않음."))),
        br(),
        tags$h2("신뢰구간 - 양측"),
        br(),
        paste0(
          (1 - input$twoprop_alpha) * 100, "% 신뢰구간: \\(p_1 - p_2 = \\hat{p}_1 - \\hat{p}_2 \\pm z_{\\alpha/2} \\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}} = \\) ",
          round(test_confint$estimate1, 3), ifelse(test_confint$estimate2 >= 0, paste0(" - ", round(test_confint$estimate2, 3)), paste0(" + ", round(abs(test_confint$estimate2), 3))), "  \\( \\pm \\) ", "\\( ( \\)", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), " * ", round(test_confint$stderr, 3), "\\( ) \\) ", "\\( = \\) ",
          "[", round(test_confint$conf.int[1], 3), "; ", round(test_confint$conf.int[2], 3), "]"
        ),
        br(),
        br(),
        tags$h2("가설 검정"),
        br(),
        paste0("1. \\(H_0 : p_1 - p_2 = \\) ", test$null.value, " vs. \\(H_1 : p_1 - p_2 \\) ", ifelse(input$twoprop_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$twoprop_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
        br(),
        paste0(
          "2. 검정 통계량 : \\(z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}}} = \\) ",
          "(", round(test$estimate1, 3), ifelse(test$estimate2 >= 0, paste0(" - ", round(test$estimate2, 3)), paste0(" + ", round(abs(test$estimate2), 3))), ifelse(test$null.value >= 0, paste0(" - ", test$null.value), paste0(" + ", abs(test$null.value))), ") / ", round(test$stderr, 3), " \\( = \\) ",
          ifelse(test$null.value >= -1 & test$null.value <= 1, round(test$statistic, 3), "Error: \\( p_1 - p_2 \\) must be \\( -1 \\leq p_1 - p_2 \\leq 1\\)")
        ),
        br(),
        paste0(
          "3. 임계값 :", ifelse(input$twoprop_alternative == "two.sided", " \\( \\pm z_{\\alpha/2} = \\pm z(\\)", ifelse(input$twoprop_alternative == "greater", " \\( z_{\\alpha} = z(\\)", " \\( -z_{\\alpha} = -z(\\)")),
          ifelse(input$twoprop_alternative == "two.sided", input$twoprop_alpha / 2, input$twoprop_alpha), "\\()\\)", " \\( = \\) ",
          ifelse(input$twoprop_alternative == "two.sided", "\\( \\pm \\)", ifelse(input$twoprop_alternative == "greater", "", " -")),
          ifelse(input$twoprop_alternative == "two.sided", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), round(qnorm(input$twoprop_alpha, lower.tail = FALSE), 3))
        ),
        br(),
        paste0("4. 결론 : ", ifelse(test$p.value < input$twoprop_alpha, "\\(H_0\\) 기각.", "\\(H_0\\) 기각 못함.")),
        br(),
        br(),
        tags$h2("해석"),
        br(),
        
        paste0( input$twoprop_alpha * 100, "% 유의수준에서, ", 
        "비율에서 차이가 ", test$null.value, " 이라는 귀무가설을 ", 
        ifelse(test$p.value < input$twoprop_alpha, "기각한다", "기각하지 않는다"), 
        " \\((p\\)-값 ", ifelse(test$p.value < 0.001, "< 0.001", paste0("\\(=\\) ", round(test$p.value, 3))), ")", ".")
        
      )
    } else if ( input$propx_twoprop == "prop_false" & input$pooledstderr_twoprop == FALSE) {
      test <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = FALSE)
      test_confint <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = "two.sided", pooled.stderr = FALSE)
      withMathJax(
        tags$h2("데이터"),
        br(),
        paste0("\\(n_1 =\\) ", round(test$n1, 3)),
        br(),
        paste0("\\(n_2 =\\) ", round(test$n2, 3)),
        br(),
        paste0("\\(\\hat{p}_1 = \\dfrac{x_1}{n_1} = \\) ", test$x1, " \\( / \\) ", test$n1, " \\( = \\) ", round(test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{p}_2 = \\dfrac{x_2}{n_2} = \\) ", test$x2, " \\( / \\) ", test$n2, " \\( = \\) ", round(test$estimate2, 3)),
        br(),
        paste0("\\(\\hat{q}_1 = 1 - \\hat{p}_1 =\\) ", round(1 - test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{q}_2 = 1 - \\hat{p}_2 =\\) ", round(1 - test$estimate2, 3)),
        br(),
        helpText(paste0("\\( n_1\\hat{p}_1 = \\) ", round(test$n1 * test$estimate1, 3), " 와 \\( n_1(1-\\hat{p}_1) = \\) ", round(test$n1 * (1 - test$estimate1), 3))),
        helpText(paste0("\\( n_2\\hat{p}_2 = \\) ", round(test$n2 * test$estimate2, 3), " 와 \\( n_2(1-\\hat{p}_2) = \\) ", round(test$n2 * (1 - test$estimate2), 3))),
        helpText(paste0("\\( n_1\\hat{p}_1 \\geq 5\\), \\( n_1(1-\\hat{p}_1) \\geq 5\\), \\( n_2\\hat{p}_2 \\geq 5\\) 와 \\( n_2(1-\\hat{p}_2) \\geq 5\\) 가정이 ", ifelse(test$n1 * test$estimate1 >= 5 & test$n1 * (1 - test$estimate1) >= 5 & test$n2 * test$estimate2 >= 5 & test$n2 * (1 - test$estimate2) >= 5, " 충족됨.", " 충족되지 않음."))),
        br(),
        tags$h2("신뢰구간 - 양측"),
        br(),
        paste0(
          (1 - input$twoprop_alpha) * 100, "% CI for \\(p_1 - p_2 = \\hat{p}_1 - \\hat{p}_2 \\pm z_{\\alpha/2} \\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}} = \\) ",
          round(test_confint$estimate1, 3), ifelse(test_confint$estimate2 >= 0, paste0(" - ", round(test_confint$estimate2, 3)), paste0(" + ", round(abs(test_confint$estimate2), 3))), "  \\( \\pm \\) ", "\\( ( \\)", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), " * ", round(test_confint$stderr, 3), "\\( ) \\) ", "\\( = \\) ",
          "[", round(test_confint$conf.int[1], 3), "; ", round(test_confint$conf.int[2], 3), "]"
        ),
        br(),
        br(),
        tags$h2("가설 검정"),
        br(),
        paste0("1. \\(H_0 : p_1 - p_2 = \\) ", test$null.value, " vs. \\(H_1 : p_1 - p_2 \\) ", ifelse(input$twoprop_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$twoprop_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
        br(),
        paste0(
          "2. 검정 통계량 : \\(z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}}} = \\) ",
          "(", round(test$estimate1, 3), ifelse(test$estimate2 >= 0, paste0(" - ", round(test$estimate2, 3)), paste0(" + ", round(abs(test$estimate2), 3))), ifelse(test$null.value >= 0, paste0(" - ", test$null.value), paste0(" + ", abs(test$null.value))), ") / ", round(test$stderr, 3), " \\( = \\) ",
          ifelse(test$null.value >= -1 & test$null.value <= 1, round(test$statistic, 3), "Error: \\( p_1 - p_2 \\) must be \\( -1 \\leq p_1 - p_2 \\leq 1\\)")
        ),
        br(),
        paste0(
          "3. 임계값 :", ifelse(input$twoprop_alternative == "two.sided", " \\( \\pm z_{\\alpha/2} = \\pm z(\\)", ifelse(input$twoprop_alternative == "greater", " \\( z_{\\alpha} = z(\\)", " \\( -z_{\\alpha} = -z(\\)")),
          ifelse(input$twoprop_alternative == "two.sided", input$twoprop_alpha / 2, input$twoprop_alpha), "\\()\\)", " \\( = \\) ",
          ifelse(input$twoprop_alternative == "two.sided", "\\( \\pm \\)", ifelse(input$twoprop_alternative == "greater", "", " -")),
          ifelse(input$twoprop_alternative == "two.sided", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), round(qnorm(input$twoprop_alpha, lower.tail = FALSE), 3))
        ),
        br(),
        paste0("4. 결론 : ", ifelse(test$p.value < input$twoprop_alpha, "\\(H_0\\) 기각.", "\\(H_0\\) 기각 못함.")),
        br(),
        br(),
        tags$h2("해석"),
        br(),
        paste0( input$twoprop_alpha * 100, "% 유의수준에서, ", 
        "비율에서 차이가 ", test$null.value, " 이라는 귀무가설을 ", 
        ifelse(test$p.value < input$twoprop_alpha, "기각한다", "기각하지 않는다"), 
        " \\((p\\)-값 ", ifelse(test$p.value < 0.001, "< 0.001", paste0("\\(=\\) ", round(test$p.value, 3))), ")", ".")
      )
    } else if ( input$propx_twoprop == "prop_true" & input$pooledstderr_twoprop == TRUE) {
      test <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = TRUE)
      test_confint <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = "two.sided", pooled.stderr = FALSE)
      withMathJax(
        tags$h2("데이터"),
        br(),
        paste0("\\(n_1 =\\) ", round(test$n1, 3)),
        br(),
        paste0("\\(n_2 =\\) ", round(test$n2, 3)),
        br(),
        paste0("\\(\\hat{p}_1 =\\) ", round(test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{p}_2 =\\) ", round(test$estimate2, 3)),
        br(),
        paste0("\\(\\hat{q}_1 = 1 - \\hat{p}_1 =\\) ", round(1 - test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{q}_2 = 1 - \\hat{p}_2 =\\) ", round(1 - test$estimate2, 3)),
        br(),
        helpText(paste0("\\( n_1\\hat{p}_1 = \\) ", round(test$n1 * test$estimate1, 3), " 와 \\( n_1(1-\\hat{p}_1) = \\) ", round(test$n1 * (1 - test$estimate1), 3))),
        helpText(paste0("\\( n_2\\hat{p}_2 = \\) ", round(test$n2 * test$estimate2, 3), " 와 \\( n_2(1-\\hat{p}_2) = \\) ", round(test$n2 * (1 - test$estimate2), 3))),
        helpText(paste0("\\( n_1\\hat{p}_1 \\geq 5\\), \\( n_1(1-\\hat{p}_1) \\geq 5\\), \\( n_2\\hat{p}_2 \\geq 5\\) 와 \\( n_2(1-\\hat{p}_2) \\geq 5\\) 가정이", ifelse(test$n1 * test$estimate1 >= 5 & test$n1 * (1 - test$estimate1) >= 5 & test$n2 * test$estimate2 >= 5 & test$n2 * (1 - test$estimate2) >= 5, " 충족됨.", " 충족되지 않음."))),
        br(),
        tags$h2("신뢰구간 - 양측"),
        br(),
        paste0(
          (1 - input$twoprop_alpha) * 100, "% CI for \\(p_1 - p_2 = \\hat{p}_1 - \\hat{p}_2 \\pm z_{\\alpha/2} \\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}} = \\) ",
          round(test_confint$estimate1, 3), ifelse(test_confint$estimate2 >= 0, paste0(" - ", round(test_confint$estimate2, 3)), paste0(" + ", round(abs(test_confint$estimate2), 3))), "  \\( \\pm \\) ", "\\( ( \\)", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), " * ", round(test_confint$stderr, 3), "\\( ) \\) ", "\\( = \\) ",
          "[", round(test_confint$conf.int[1], 3), "; ", round(test_confint$conf.int[2], 3), "]"
        ),
        br(),
        br(),
        tags$h2("가설 검정"),
        br(),
        paste0("1. \\(H_0 : p_1 - p_2 = \\) ", test$null.value, " vs. \\(H_1 : p_1 - p_2 \\) ", ifelse(input$twoprop_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$twoprop_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
        br(),
        paste0("2. 검정 통계량 : \\(z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\hat{p}(1-\\hat{p})\\Big(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\Big)}} \\) "),
        br(),
        paste0("여기서 ", "\\( \\hat{p} = \\dfrac{n_1 \\hat{p}_1 + n_2 \\hat{p}_2}{n_1 + n_2} = \\) ", "(", test$n1, " * ", round(test$estimate1, 3), " + ", test$n2, " * ", round(test$estimate2, 3), ") / (", test$n1, " + ", test$n2, ") = ", round(test$pooled.phat, 3)),
        br(),
        paste0(
          "\\( \\Rightarrow z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\hat{p}(1-\\hat{p})\\Big(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\Big)}} = \\) ",
          "(", round(test$estimate1, 3), ifelse(test$estimate2 >= 0, paste0(" - ", round(test$estimate2, 3)), paste0(" + ", round(abs(test$estimate2), 3))), ifelse(test$null.value >= 0, paste0(" - ", test$null.value), paste0(" + ", abs(test$null.value))), ") / ", round(test$stderr, 3), " \\( = \\) ",
          ifelse(test$null.value >= -1 & test$null.value <= 1, round(test$statistic, 3), "Error: \\( p_1 - p_2 \\) must be \\( -1 \\leq p_1 - p_2 \\leq 1\\)")
        ),
        br(),
        paste0(
          "3. 임계값 :", ifelse(input$twoprop_alternative == "two.sided", " \\( \\pm z_{\\alpha/2} = \\pm z(\\)", ifelse(input$twoprop_alternative == "greater", " \\( z_{\\alpha} = z(\\)", " \\( -z_{\\alpha} = -z(\\)")),
          ifelse(input$twoprop_alternative == "two.sided", input$twoprop_alpha / 2, input$twoprop_alpha), "\\()\\)", " \\( = \\) ",
          ifelse(input$twoprop_alternative == "two.sided", "\\( \\pm \\)", ifelse(input$twoprop_alternative == "greater", "", " -")),
          ifelse(input$twoprop_alternative == "two.sided", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), round(qnorm(input$twoprop_alpha, lower.tail = FALSE), 3))
        ),
        br(),
        paste0("4. 결론 : ", ifelse(test$p.value < input$twoprop_alpha, "\\(H_0\\) 기각.", "\\(H_0\\) 기각 못함.")),
        br(),
        br(),
        tags$h2("해석"),
        br(),
        
        paste0( input$twoprop_alpha * 100, "% 유의수준에서, ", 
        "비율에서 차이가 ", test$null.value, " 이라는 귀무가설을 ", 
        ifelse(test$p.value < input$twoprop_alpha, "기각한다", "기각하지 않는다"), 
        " \\((p\\)-값 ", ifelse(test$p.value < 0.001, "< 0.001", paste0("\\(=\\) ", round(test$p.value, 3))), ")", ".")
      )
    } else if ( input$propx_twoprop == "prop_false" & input$pooledstderr_twoprop == TRUE) {
      test <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = TRUE)
      test_confint <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = "two.sided", pooled.stderr = FALSE)
      withMathJax(
        tags$h2("데이터"),
        br(),
        paste0("\\(n_1 =\\) ", round(test$n1, 3)),
        br(),
        paste0("\\(n_2 =\\) ", round(test$n2, 3)),
        br(),
        paste0("\\(\\hat{p}_1 = \\dfrac{x_1}{n_1} = \\) ", test$x1, " \\( / \\) ", test$n1, " \\( = \\) ", round(test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{p}_2 = \\dfrac{x_2}{n_2} = \\) ", test$x2, " \\( / \\) ", test$n2, " \\( = \\) ", round(test$estimate2, 3)),
        br(),
        paste0("\\(\\hat{q}_1 = 1 - \\hat{p}_1 =\\) ", round(1 - test$estimate1, 3)),
        br(),
        paste0("\\(\\hat{q}_2 = 1 - \\hat{p}_2 =\\) ", round(1 - test$estimate2, 3)),
        br(),
        helpText(paste0("\\( n_1\\hat{p}_1 = \\) ", round(test$n1 * test$estimate1, 3), " 와 \\( n_1(1-\\hat{p}_1) = \\) ", round(test$n1 * (1 - test$estimate1), 3))),
        helpText(paste0("\\( n_2\\hat{p}_2 = \\) ", round(test$n2 * test$estimate2, 3), " 와 \\( n_2(1-\\hat{p}_2) = \\) ", round(test$n2 * (1 - test$estimate2), 3))),
        helpText(paste0("\\( n_1\\hat{p}_1 \\geq 5\\), \\( n_1(1-\\hat{p}_1) \\geq 5\\), \\( n_2\\hat{p}_2 \\geq 5\\) 와 \\( n_2(1-\\hat{p}_2) \\geq 5\\) 가정이", ifelse(test$n1 * test$estimate1 >= 5 & test$n1 * (1 - test$estimate1) >= 5 & test$n2 * test$estimate2 >= 5 & test$n2 * (1 - test$estimate2) >= 5, " 충족됨.", " 충족되지 않음."))),
        br(),
        tags$h2("신뢰구간 - 양측"),
        br(),
        paste0(
          (1 - input$twoprop_alpha) * 100, "% CI for \\(p_1 - p_2 = \\hat{p}_1 - \\hat{p}_2 \\pm z_{\\alpha/2} \\sqrt{\\dfrac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\dfrac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}} = \\) ",
          round(test_confint$estimate1, 3), ifelse(test_confint$estimate2 >= 0, paste0(" - ", round(test_confint$estimate2, 3)), paste0(" + ", round(abs(test_confint$estimate2), 3))), "  \\( \\pm \\) ", "\\( ( \\)", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), " * ", round(test_confint$stderr, 3), "\\( ) \\) ", "\\( = \\) ",
          "[", round(test_confint$conf.int[1], 3), "; ", round(test_confint$conf.int[2], 3), "]"
        ),
        br(),
        br(),
        tags$h2("가설 검정"),
        br(),
        paste0("1. \\(H_0 : p_1 - p_2 = \\) ", test$null.value, " vs. \\(H_1 : p_1 - p_2 \\) ", ifelse(input$twoprop_alternative == "two.sided", "\\( \\neq \\) ", ifelse(input$twoprop_alternative == "greater", "\\( > \\) ", "\\( < \\) ")), test$null.value),
        br(),
        paste0("2. 검정 통계량 : \\(z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\hat{p}(1-\\hat{p})\\Big(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\Big)}} \\) "),
        br(),
        paste0("여기서 ", "\\( \\hat{p} = \\dfrac{n_1 \\hat{p}_1 + n_2 \\hat{p}_2}{n_1 + n_2} = \\) ", "(", test$n1, " * ", round(test$estimate1, 3), " + ", test$n2, " * ", round(test$estimate2, 3), ") / (", test$n1, " + ", test$n2, ") = ", round(test$pooled.phat, 3)),
        br(),
        paste0(
          "\\( \\Rightarrow z_{obs} = \\dfrac{(\\hat{p}_1 - \\hat{p}_2) - (p_1 - p_2)}{\\sqrt{\\hat{p}(1-\\hat{p})\\Big(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\Big)}} = \\) ",
          "(", round(test$estimate1, 3), ifelse(test$estimate2 >= 0, paste0(" - ", round(test$estimate2, 3)), paste0(" + ", round(abs(test$estimate2), 3))), ifelse(test$null.value >= 0, paste0(" - ", test$null.value), paste0(" + ", abs(test$null.value))), ") / ", round(test$stderr, 3), " \\( = \\) ",
          ifelse(test$null.value >= -1 & test$null.value <= 1, round(test$statistic, 3), "Error: \\( p_1 - p_2 \\) must be \\( -1 \\leq p_1 - p_2 \\leq 1\\)")
        ),
        br(),
        paste0(
          "3. 임계값 :", ifelse(input$twoprop_alternative == "two.sided", " \\( \\pm z_{\\alpha/2} = \\pm z(\\)", ifelse(input$twoprop_alternative == "greater", " \\( z_{\\alpha} = z(\\)", " \\( -z_{\\alpha} = -z(\\)")),
          ifelse(input$twoprop_alternative == "two.sided", input$twoprop_alpha / 2, input$twoprop_alpha), "\\()\\)", " \\( = \\) ",
          ifelse(input$twoprop_alternative == "two.sided", "\\( \\pm \\)", ifelse(input$twoprop_alternative == "greater", "", " -")),
          ifelse(input$twoprop_alternative == "two.sided", round(qnorm(input$twoprop_alpha / 2, lower.tail = FALSE), 3), round(qnorm(input$twoprop_alpha, lower.tail = FALSE), 3))
        ),
        br(),
        paste0("4. 결론 : ", ifelse(test$p.value < input$twoprop_alpha, "\\(H_0\\) 기각.", "\\(H_0\\) 기각 못함.")),
        br(),
        br(),
        tags$h2("해석"),
        br(),
        
        paste0( input$twoprop_alpha * 100, "% 유의수준에서, ", 
        "비율에서 차이가 ", test$null.value, " 이라는 귀무가설을 ", 
        ifelse(test$p.value < input$twoprop_alpha, "기각한다", "기각하지 않는다"), 
        " \\((p\\)-값 ", ifelse(test$p.value < 0.001, "< 0.001", paste0("\\(=\\) ", round(test$p.value, 3))), ")", ".")


      )
    } 
  })
  
```

Column {data-width=400}
-------------------------------------
   
### 시각화


```{r two-proprotion-viz, out.width="100%", eval = TRUE}
renderPlotly({  
if (input$propx_twoprop == "prop_true" & input$pooledstderr_twoprop == FALSE) {
        test <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = FALSE)
      } else if (input$propx_twoprop == "prop_false" & input$pooledstderr_twoprop == FALSE) {
        test <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = FALSE)
      } else if (input$propx_twoprop == "prop_true" & input$pooledstderr_twoprop == TRUE) {
        test <- prop.z.test2(x1 = input$n1_twoprop * input$p1_twoprop, x2 = input$n2_twoprop * input$p2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = TRUE)
      } else if (input$propx_twoprop == "prop_false" & input$pooledstderr_twoprop == TRUE) {
        test <- prop.z.test2(x1 = input$x1_twoprop, x2 = input$x2_twoprop, n1 = input$n1_twoprop, n2 = input$n2_twoprop, p0 = input$twoprop_h0, conf.level = 1 - input$twoprop_alpha, alternative = input$twoprop_alternative, pooled.stderr = TRUE)
      }
      if (input$twoprop_alternative == "two.sided") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x < qnorm(input$twoprop_alpha / 2, mean = 0, sd = 1, lower.tail = FALSE) & x > qnorm(input$twoprop_alpha / 2, mean = 0, sd = 1) ] <- NA
          return(y)
        }
      } else if (input$twoprop_alternative == "greater") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x < qnorm(input$twoprop_alpha, mean = 0, sd = 1, lower.tail = FALSE) ] <- NA
          return(y)
        }
      } else if (input$twoprop_alternative == "less") {
        funcShaded <- function(x) {
          y <- dnorm(x, mean = 0, sd = 1)
          y[x > qnorm(input$twoprop_alpha, mean = 0, sd = 1, lower.tail = TRUE) ] <- NA
          return(y)
        }
      }
      p <- ggplot(data.frame(x = c(qnorm(0.999, mean = 0, sd = 1, lower.tail = FALSE), qnorm(0.999, mean = 0, sd = 1, lower.tail = TRUE))), aes(x = x)) +
        
        geom_area(stat="function", fun = dnorm, fill="gray90", args = list(mean = 0, sd = 1)) +
        geom_area(stat="function", fun = funcShaded, fill = "sky blue", alpha = 0.8) +

        theme_minimal() +
        geom_vline(xintercept = test$statistic, color = "steelblue") +
        geom_text(aes(x = test$statistic, label = paste0("검정 통계량 = ", round(test$statistic, 3)), y = 0.2), colour = "steelblue", angle = 90, vjust = 1.3, text = element_text(size = 11)) +
        ggtitle(paste0("정규분포 N(0,1)")) +
        theme(plot.title = element_text(face = "bold", hjust = 0.5)) +
        ylab("밀도") +
        xlab("x")
      plotly::ggplotly(p)
  })


```


### 데이터


```{r two-proportion-data}

renderTable({

prop_dat1 <- rbinom(input$n1_twoprop, 1, input$p1_twoprop)
prop_dat2 <- rbinom(input$n2_twoprop, 1, input$p2_twoprop)

tibble(변수1 = prop_dat1,
       변수2 = prop_dat2 ) %>%
  xtable::xtable(align="ccc")

})
```


