---
title: "hsData - 실용통계"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
vertical_layout: fill
theme: lumen
logo: ../assets/hsData-favicon-60x60.png
css: ../assets/hsData.css
includes:
  in_header: ../assets/google_analytics.html
editor_options: 
  chunk_output_type: console
---
  
  
```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(knitr.duplicate.label = 'allow')
## 0. R 팩키지 ------
library(flexdashboard)
library(tidyverse)
library(janitor)
library(extrafont)
loadfonts()
library(here)
library(fs)
library(glue)
library(gt)
library(plotly)
library(ggrepel)
library(crosstalk)

# GGPLOT THEME ------------------------------------------------------------

theme_election <- function(..., font = "MaruBuri") {
  
  theme_bw(base_family = font)  %+replace%
    
    theme(
      
      #grid elements
      panel.grid.major.x = element_line(color='gray75'),
      panel.grid.minor.x = element_blank(),
      # axis.ticks = element_blank(),          #strip axis ticks
      
      #since theme_minimal() already strips axis lines, 
      #we don't need to do that again
      
      #text elements
      plot.title = element_text(             #title
        family = font,            #set font family
        size = 21,                #set font size
        face = 'bold',            #bold typeface
        hjust = 0,                #left align
        vjust = 1),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
        family = font,            #font family
        hjust = 0,                #left align        
        size = 15),               #font size
      
      plot.caption = element_text(           #caption
        family = font,            #font family
        size = 12,                 #font size
        hjust = 1),               #right align
      
      axis.title = element_text(             #axis titles
        family = font,            #font family
        size = 15),               #font size
      
      axis.text.x = element_text(            #margin for axis text
        margin=margin(5, b = 10),
        size = rel(1.5),
        family = font, face="bold"),
      
      axis.text.y = element_text(
        size = rel(1.5),
        colour = "gray35", 
        family = font, face="bold"),
      
      strip.text.x = element_text(
        size = rel(1.5), 
        colour = "black", family = font, face="bold" ),
      
      strip.background = element_rect(fill="gray95"),
      
      legend.position = "top",
      legend.title=element_text(size=17),
      legend.text=element_text(size=15)
    )
}

```



데이터셋 {data-icon="fa-car-alt"}
=====================================  

Column {data-width=200}
-------------------------------------

### 데이터



```{r hsdata-select}

# devtools::install_github("bit2r/hsData")
library(hsData)

hsData_names <- data(package="hsData")$results %>% 
  as.data.frame() %>% 
  pull(Item)

# listviewer::jsonedit(data(package="hsData"))

hsData_tbl <- data(package="hsData")$results %>% 
  as.data.frame() %>% 
  select(name = Item, Title,) %>% 
  mutate(data_string = glue::glue("hsData::{name}")) %>% 
  mutate(data = map(data_string, lazyeval::lazy_eval ) ) %>% 
  select(name, 설명 = Title, data)

library(tidyverse)  

shared_ev <- SharedData$new(hsData_tbl, key = ~name)

filter_select(
  id = "데이터",
  label = "데이터셋",
  sharedData = shared_ev,
  group = ~name,
  multiple = FALSE,
  allLevels = FALSE
)



```


Column {data-width=800}
-------------------------------------

### 데이터셋 상세

```{r about-dataset}

DT::datatable(shared_ev)

```
